### ISSUE TITLE
Incorrect event name in README example.

### ISSUE THREAD

**Issue by confusingstraw** [cheton/react-infinite-tree#1]
Hi, first off, thanks for making the component, I'm just getting started with using it.

One thing I'd like to point out is that the example in the README makes use of the onSelect event, but I found when using the library that the event is actually called onSelectNode.

**Comment by cheton** [comment]
Thanks for the correction. I've updated the README

**Comment by cheton** [comment]
Typos in README and examples are fixed in v0.2.2.
