### ISSUE TITLE
how to get the scroll percent?

### ISSUE THREAD

**Issue by SixYearsInFebruary** [cheton/react-infinite-tree#10]
On the gif of your demo, maybe the scroll percent could be get, but I didn't find any API to do this. Do you have some method? @cheton 
the onScroll function called by react-tiny-virtual-list don't without percent.

**Comment by cheton** [comment]
```js
onScroll={(scrollOffset, event) => {
    const child = event.target.firstChild;
    const treeViewportHeight = 400; // The value of tree height
    const scrollPercent = (scrollOffset / (child.scrollHeight - treeViewportHeight) * 100).toFixed(2);
}}
```

**Comment by SixYearsInFebruary** [comment]
I had found this way to calculate the percent, thx.
Suggest to make it as API. @cheton
