### ISSUE TITLE
shouldLoadNodes runtime error appears

### ISSUE THREAD

**Issue by Kotuhan** [cheton/react-infinite-tree#12]
Hi!
shouldLoadNodes passed to the div component and this error appears

Warning: React does not recognize the `shouldLoadNodes` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `shouldloadnodes` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

Could you, please, fix it?

**Comment by cheton** [comment]
Fixed in [v1.0.0-alpha.6](https://github.com/cheton/react-infinite-tree/releases/tag/v1.0.0-alpha.6)
