### ISSUE TITLE
Error when trying to open a closed node

### ISSUE THREAD

**Issue by Raathigesh** [cheton/react-infinite-tree#13]
I'm using the `loadData()` method to set the data to the tree. But when I close the node and try to open it again, there is an error which says `Cannot open node with the given node id:`.

The tree looks like below.

![image](https://user-images.githubusercontent.com/3108160/39957975-3779b024-563f-11e8-9193-c883259d72aa.png)

The first node (`examples`) expands and closes without an issue but the other nodes won't expand after closing it for the very first time. Any pointers would be helpful 😄

**Comment by cheton** [comment]
Can you output your tree structure including the node id? Thanks.

**Comment by Raathigesh** [comment]
I used react virtualized directly and sorry I couldn't dig into the issue further. Thank you though! Closing this for now.
