### ISSUE TITLE
not working with react-native

### ISSUE THREAD

**Issue by bradrust** [cheton/react-infinite-tree#4]
I am not clear on whether or not react-infinite-tree is supposed to work with a react-native project but I am blocked by babel related issues.  The react-native generated project doesn't have a webpack.conf.js but does have .babelrc with a preset of "react-native" (instead of "react").

`node_modules\react-infinite-tree\lib\index.js: Unknown option: foreign.Children.` is the current block after I added "es2015-loose", "stage-0" to my .babelrc.

here are some dependencies...

`"babel-plugin-transform-class-properties": "^6.11.5",`
`"babel-preset-react-native": "^1.9.0",`
`"babel-preset-es2015-loose": "^8.0.0",`
`"babel-preset-stage-0": "^6.5.0",`
`"babel-register": "^6.11.6",`
`"babel-eslint": "^6.1.0",`
`"babel-preset-es2015": "^6.9.0",`
`"babel-preset-stage-0": "^6.5.0",`
`"infinite-tree": "^1.7.1",`
`"react-infinite-tree": "^0.5.1",`

**Comment by cheton** [comment]
I'm afraid that `react-infinite-tree` may not be able to work with react-native since this component itself is just a wrapper for the `infinite-tree` library, accesses to HTML DOM nodes and browser APIs like `element.querySelector` may cause such kind of errors with react-native.
