### ISSUE TITLE
forced reload

### ISSUE THREAD

**Issue by manubamba** [cheton/react-infinite-tree#5]
is there a way I can use the API to reload the children of a node (using the `loadNodes` passed to it)?
Cheers

**Comment by cheton** [comment]
You can try calling [infinite-tree api](https://github.com/cheton/infinite-tree/wiki/Functions:-Tree) as shown below:

``` js
class App extends React.Component {
    tree = null;

    reload(parentNode) {
        const childNodes = [
            { id: 'first-child' },
            { id: 'second-child', children: [ { id: 'third-child' } ] }
        ];
        this.tree.removeChildNodes(parentNode);
        this.tree.addChildNodes(childNodes, parentNode);
    }
    render() {
        return (
            <InfiniteTree
                ref={(c) => this.tree = c.tree}
                // other props ...
            />
        );
    }
}
```

**Comment by manubamba** [comment]
The problem with this solution is that I am using `loadNodes` function to fetch my nodes on demand. I cannot call `addChildNodes` because I don't have the child nodes.
This is what I am doing for now, but I don't find it elegant.

```
tree.removeChildNodes(node);    
node.loadOnDemand = true;
tree.closeNode(node, {silent: true});
tree.openNode(node, {silent: true});
```

**Comment by cheton** [comment]
You can update [infinite-tree](https://github.com/cheton/infinite-tree) peer dependency to [v1.7.1](https://github.com/cheton/infinite-tree/releases/tag/v1.7.1) which resolved an issue that removeChildNodes cannot close the parent node after removing its child nodes.

Commit: https://github.com/cheton/infinite-tree/commit/968485fd95d9cec69dcf86cf91f8696c972fa6fb

So you don't need to use the following lines:

``` js
node.loadOnDemand = true;
tree.closeNode(node, {silent: true});
```
